PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
 
SELECT ?company ?locationCity ?locationCountry ?keyPeople ?foundingYear ?industry ?netIncome ?operatingIncome ?revenue ?numberOfEmployees
WHERE {
 
?company rdf:type dbo:Company .
?company dbo:numberOfEmployees ?numberOfEmployees .
?company dbp:locationCity ?locationCity.
?company dbp:locationCountry ?locationCountry.
optional{?company dbp:keyPeople ?keyPeople .}
optional{?company dbo:foundingYear ?foundingYear .}
optional{?company dbo:industry ?industry .}
optional{?company dbo:netIncome ?netIncome .}
optional{?company dbo:operatingIncome ?operatingIncome .}
optional{?company dbo:revenue ?revenue .}
 
 
FILTER(?numberOfEmployees>100)
}