PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>

SELECT distinct ?company 
group_concat(distinct str(?locationCity);separator=";;") as ?locationCity 
group_concat(distinct str(?locationCountry);separator=";;") as ?locationCountry
group_concat(distinct str(?keyPeople);separator=";;") as ?keyPeople 
group_concat(distinct str(?foundingYear);separator=";;") as ?foundingYear
group_concat(distinct str(?industry);separator=";;") as ?industry
max(?netIncome) as ?netIncome 
max(?operatingIncome) as ?operatingIncome
max(?revenue) as ?revenue

WHERE {

?company rdf:type dbo:Company .
?company dbo:numberOfEmployees ?numberOfEmployees .
?company dbp:locationCity ?locationCity.
?company dbp:locationCountry ?locationCountry.
optional{?company dbp:keyPeople ?keyPeople .}
optional{?company dbo:foundingYear ?foundingYear .}
optional{?company dbo:industry ?industry .}
optional{?company dbo:netIncome ?netIncome .}
optional{?company dbo:operatingIncome ?operatingIncome .}
optional{?company dbo:revenue ?revenue .}


FILTER(?numberOfEmployees>100)
}