PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>

SELECT distinct ?label Max(?pop)as ?population  Max(?areaTotal)as ?areaTotal
Max(?elevation)as ?elevation ?country 
WHERE {
{?location rdf:type dbo:City  .}
union
{?location rdf:type dbo:AdministrativeRegion  .}
union
{?location rdf:type dbo:Location  .}
?location rdfs:label ?label .
?location dbo:areaTotal ?areaTotal .
?location dbo:elevation ?elevation .
?location dbo:country ?country .
?location dbo:populationTotal ?pop .
FILTER((lang(?label) = 'en'))
}

